version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    networks:
      - backnet

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    ports:
      - '8080:8080'
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - backnet
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - backnet
    cap_add:
      - SYS_NICE

networks:
  backnet:
    driver: bridge

volumes:
  mysql-data:
