version: '3'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - '8080:8080'

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    expose:
      - 3306
      - 33060

volumes:
  mysql-data:
