FROM python:3.8-slim

WORKDIR /app

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get -y install iputils-ping

RUN pip install pipenv

COPY Pipfile.lock ./

RUN pipenv sync --system

COPY libbbs ./libbbs/

COPY main.py model.py ./

CMD [ "python", "main.py" ]
